on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      GCP_PROJECT_ID:
        required: true
        type: string
      GCP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
        type: string
      GCP_SERVICE_ACCOUNT:
        required: true
        type: string
      GH_APP_ID:
        required: true
        type: string
      WEBHOOK_PATH:
        required: true
        type: string
    secrets:
      GH_PRIVATE_KEY:
        required: true
      GH_WEBHOOK_SECRET:
        required: true
      CHAT_GPT_API_KEY:
        required: true

jobs:
  provision:
    name: 'Provision and deploy'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate with GCP'
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ inputs.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ inputs.GCP_SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ inputs.GCP_PROJECT_ID }}

      - name: Update snooze-bot secrets in GCP Secret Manager
        run: |
          printf -- "${{ secrets.GH_PRIVATE_KEY }}"    | gcloud secrets versions add reviewbot-github-private-key-${{ inputs.environment }} --data-file=-
          printf -- "${{ secrets.GH_WEBHOOK_SECRET }}" | gcloud secrets versions add reviewbot-github-webhook-secret-${{ inputs.environment }} --data-file=-
          printf -- "${{ secrets.CHAT_GPT_API_KEY }}" | gcloud secrets versions add reviewbot-chat-gpt-api-key-${{ inputs.environment }} --data-file=-

      - name: 'Deploy webhook to Cloud Run'
        id: deploy-webhook
        run: >-
          gcloud functions deploy ${{ inputs.WEBHOOK_PATH }}
          --project="${{ inputs.GCP_PROJECT_ID }}"
          --runtime=nodejs18
          --source=.
          --entry-point=webhook
          --set-secrets=PRIVATE_KEY=projects/${{ inputs.GCP_PROJECT_ID }}/secrets/reviewbot-github-private-key-${{ inputs.environment }}:latest
          --set-secrets=WEBHOOK_SECRET=projects/${{ inputs.GCP_PROJECT_ID }}/secrets/reviewbot-github-webhook-secret-${{ inputs.environment }}:latest
          --set-env-vars=APP_ID="${{ inputs.GH_APP_ID }}"
          --set-env-vars=CHAT_GPT_API_KEY="${{ inputs.CHAT_GPT_API_KEY }}"
          --trigger-http
          --allow-unauthenticated
          --region=us-central1
          --gen2

      - name: 'Show summary'
        run: >-
          echo "App successfully deployed."
